# development environment based on x86 
FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential python3 python3-pip scons git m4 \
    zlib1g-dev libprotobuf-dev protobuf-compiler \
    libgoogle-perftools-dev libboost-all-dev \
    pkg-config wget ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/gem5